version: '3'

services:
  # PHP/Apacheサービス
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html

  # MySQLサービス
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  # 追加
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password


volumes:
  db_data: